### ISSUE TITLE
Left over lorem ipsum

### ISSUE THREAD

**Issue by codyburley** [gsabater/Steam-Backlog#100]
There's some left over placeholder lorem ipsum under the popular categories section of the home page.

![image](https://user-images.githubusercontent.com/106035861/191836247-18dac281-0a08-403d-8064-3b732a74ba73.png)

**Comment by gsabater** [comment]
Thanks for your heads up.
I haven't answered before because the site was left as-is.

I comment to say that I will mark this as wontfix, because i'm working and steam backlog will be replaced by https://backlog.rip
