### ISSUE TITLE
Deselect games when adding them to a backlog category

### ISSUE THREAD

**Issue by gsabater** [gsabater/Steam-Backlog#57]
```
when selecting multiple games and add them to a category, the selection stays, 
making it annoying to select other games many times I forgot to push deselect and 
ended up with games in other categories
```

Suggested by Stremon via Chat

**Comment by gsabater** [comment]
I don't know if I would make this the default behaviour, but maybe we could make an option, a button or a switch to have the selection removed after adding the games to a category.

**Comment by MakoSipper** [comment]
Oh, I just suggested the opposite of this. For unselecting all games after placing them, you could just refresh the page as a workaround, but if you want to keep them selected, there's no way around now.

I think what would really be best for all cases would be a "Select/Unselect all [filtered games]". It would help in many other situations.

**Comment by gsabater** [comment]
As I waid in #59, we have reverted the change that unmarked or cleared the selection of games after adding them to a Backlog category. And we want to add a switch to give users more control over this feature.

**Comment by gsabater** [comment]
Closing as now the default selection modal has an option to clear the selection (active by default) after adding the games to your backlog.

![modal](https://user-images.githubusercontent.com/4948172/54932662-765c9100-4f1b-11e9-96c3-53295179ac1e.PNG)
