### ISSUE TITLE
Unable to access all my backlogs (only "Playing")

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#58]
This looks like a new issue, on Chrome. I can only see my "Playing" backlog, but the tabs for other categories are gone.

On Firefox, the page doesn't seem to load properly (game cards don't load, new dropdrown seems off etc.)

**Comment by MakoSipper** [comment]
Looks fixed now...

**Comment by gsabater** [comment]
Closing after two weeks of inactivity.
Assuming it's working.

Reopen if needed.
