### ISSUE TITLE
Suggestion: Never hide games in backlog while looking the backlog

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#60]
Even if the option is on, because this option makes no sense in the backlog. It should apply only to wishlist, library, and all steam games. Right now, it forces me to turn it on/off every time I move from the backlog to the library and vice versa.

**Comment by gsabater** [comment]
Hello @MakoSipper , you mean the `"Hide games already in my backlog"` option?
That makes sense, we will take a look at it.

Thanks

**Comment by MakoSipper** [comment]
Yes, that very same option ;)

**Comment by gsabater** [comment]
@MakoSipper 
I forgot to mention, but this was implemented a week ago.
The `"Hide games already in my backlog"` option now won't hide games when you are browsing your backlog. 

---

Fixed in October release.
Complete changelog in https://steam-backlog.com/changelog
