### ISSUE TITLE
Dropdowns showing behind the game cards

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#64]
I'm not sure how to trigger this, but I've seen this happen a few times over the last month. I can't always reproduce it, but it seems to affect all dropdowns when it happens.

Example:
![chrome_2018-10-19_23-45-07](https://user-images.githubusercontent.com/16372995/47250551-443d8500-d3f9-11e8-9494-4ccbb453dd41.png)

**Comment by gsabater** [comment]
Also reported by Rwig via Chat

https://i.imgur.com/2x86Mur.png

**Comment by gsabater** [comment]
We have solved this issue on the new layout. Now it's possible to select multiple games and the dropdowns won't stay behind.

In beta until March that the new layout will replace the current one.

---

Fixed in January 2019 release.
Complete changelog in https://steam-backlog.com/changelog
