### ISSUE TITLE
Add link to steam store on game info

### ISSUE THREAD

**Issue by spitfireCH** [gsabater/Steam-Backlog#78]
When browsing the games and clicking a game to get more info on it, a direct link to the steam store could be useful. You can already get there by clicking on "Steam Score", but that's not very obvious.

It's also entirely possible the link is already there and I simply can't see it (like the cheese in the fridge in front of my nose which is magically invisible to me but not to my wife)... ;)

**Comment by gsabater** [comment]
Hello @spitfireCH, 

We are actually working in something called "button section" with buttons to external sources like the steam store, the humble store, etc. 

The main reason this hasn't been implemented yet is because we literally don't know where to put those buttons. But we are trying to have this asap.

Thanks for the feedback.

**Comment by spitfireCH** [comment]
Sounds like a great idea, thanks for looking into it!

**Comment by gsabater** [comment]
Hello @spitfireCH 

We have added a couple of buttons to the game modal.
Now you will see buttons to launch / install a game, a button to download a free demo (when available and you don't own the game), and a button to the steam store.

We don't love how are they displayed, so we might change it, but at least, they are there and I don't think that they will be removed.

### Screenshots:
![captura de pantalla 2019-02-18 00 13 28](https://user-images.githubusercontent.com/4948172/52920941-38fc5680-3312-11e9-900d-238bd6e64b3b.png)
![captura de pantalla 2019-02-18 00 14 19](https://user-images.githubusercontent.com/4948172/52920942-3a2d8380-3312-11e9-95b6-becc62a8e0a6.png)

Thanks for your feedback. 
We love receiving it!

---

Implemented in February 2019 release.
Complete changelog at https://steam-backlog.com/changelog

**Comment by spitfireCH** [comment]
Very nice! Thank you very much!
