### ISSUE TITLE
Filter buffer when adding games to a collection

### ISSUE THREAD

**Issue by spitfireCH** [gsabater/Steam-Backlog#80]
When searching for games to be added to a collection (edit collection screen), the old (unbuffered) filter method is used. Adding a buffer could help here, too.

**Comment by gsabater** [comment]
Hello @spitfireCH 

You are right, but the whole collection area uses the old filtering system. We cannot apply the buffer without updating a lot of inner code. Which we want to do, with a lot of other improvements to the collection section.

**Comment by gsabater** [comment]
Hello @spitfireCH 
We have updated the create collection logic, and it has been updated to use the default filtering method with search buffer.

Thanks a lot for your continued contributions to the site. 
---

Implemented in March 2019 release.
Complete changelog at https://steam-backlog.com/changelog

**Comment by spitfireCH** [comment]
Thx! :) 👍
