### ISSUE TITLE
[BUG] Apps with incorrect names

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#82]
![image](https://user-images.githubusercontent.com/16372995/55683509-ea813680-5916-11e9-9e57-9e45d1964bf1.png)
^ For example.

Thankfully, I was able to find it using the game id. ;)

This might or not be related to issue #81

**Comment by MakoSipper** [comment]
Also, I'm sure this is a new(-ish?) issue. I'm sure it wasn't called "Mabinogi" back when I added it to my backlog.

**Comment by gsabater** [comment]
Hello @MakoSipper 

You are right, this problem has been caused due to recent changes to the scraping system. 
I made those changes to remove demos and other non-games apps from database, as well as reduce database size to increase loading times and include store links to games. In the process, a new bug appeared when the system updates a game that is removed from steam. All the following games updated in that batch have been some attributes changed.

This is something I detected and solved last week, but now some games are affected with this until I solve it manually or until they are scraped again (every game is updated every 3 months or so).

Sorry for the "technical" talk, but I wanted to explain the reason of this. You can see more of this if you search "Borderlands 2" in "all games".

I will manually update that game, and any other that i can see. 
If you detect any more of those wrong games, please, let me know.

I'm starting to think in creating a page with a form where users could change wrong data.
What do you think about it?

Thanks a lot

**Comment by MakoSipper** [comment]
> I'm starting to think in creating a page with a form where users could change wrong data.
> What do you think about it?

You could try, if it's not too much trouble. If people start abusing it or if you're having way too much trouble dealing with those, you can always take it down :)

**Comment by MakoSipper** [comment]
I've also noticed that there are many games wrongfully name "Mabinogi".

**Comment by gsabater** [comment]
> You could try, if it's not too much trouble. If people start abusing it or if you're having way too much trouble dealing with those, you can always take it down :)
I don't think that people would abuse a helping form, and it could help a lot to fill wrong data for removed games from steam or the infamous problem with game release dates (do you remember?)

> I've also noticed that there are many games wrongfully name "Mabinogi".
Ok, tomorrow i will refresh the scraping for any game called borderlands 2 and mabinogi.

 I will keep this issue open for a while and if you spot any other game with wrong name, just let me know. I will close the issue once i think all the data is fixed.

Thanks

**Comment by gsabater** [comment]
### Update

* 8 Apps called Mabinogi updated
* Appids: 212200, 409320, 344040, 541160, 673000, 280040, 477160, 212210
* _212200 and 212210 have been removed from db._

Those changes should be visible after db is updated and cache is refreshed.
I will test in 24hours in incognito mode.

**Comment by gsabater** [comment]
### Update

* 21 apps called "Borderlands 2 RU" updates
* Appids: 217610, 217630, 229150, 232990, 229160, 229170, 257330, 239680, 249920, 268610, 217490, 217550, 248270, 254170, 238300, 217570, 545250, 21730, 351970, 254180, 217590
* _217610, 217630, 229150, 229160, 229170, 257330, 239680, 217490, 217550, 254170, 217570, 254180 and 217590 have been removed from db._

Those changes should be visible after db is updated and cache is refreshed.
I will test in 24hours in incognito mode.

**Comment by gsabater** [comment]
### Update

* 21 apps called "Trials Rising" updated
* Appids: 641080, 928770, 1003010, 1040900, 1041670, 1039370, 809230, 1011470, 1020430, 924180, 1041430, 1020440, 924840, 1028520, 998570, 413610, 1042090, 1008300
* _  928770, 924180 and 924840, have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update

* 21 apps called "La Corda d'Oro Octave - 金色のコルダ オクターヴ" fixed
* Appids: 1040040,1044640,1011350,1028760,1033620,1042310,1021830,742510,846590,623870,413950,1001470,387580,826620,419580,1005410,1019230,1033820,1041240,1036120,1041750,1015620,997950,1040680,1037860,1042460,1019420,1033490,1035280,998320,998310,998290,998280,998260,998250,998240,1041660,998140,998230,1040200,998210,998200,1027120,998190,998180,998170,998160,1011210,998000,978310,998030,998040,998050,862630,998060,998070,931520,998080,998090,998100,998110,998120,998130

* _846590, 623870, 413950, 1001470, 387580, 826620, 419580, 998310, 998290, 998280, 998260, 998250, 998240, 998140, 998230, 998210, 998200, 998190, 998180, 998170, 998160, 1011210, 998000, 978310, 998030, 998040, 998050, 862630, 998060, 998070, 931520, 998080, 998090, 998100, 998110, 998120 and 998130  have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Skullgirls ∞Endless Beta∞"

* 5 apps fixed
* Appids: 275170, 340450, 12770, 471010, 208610 

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "(Depreciated)"

* 5 apps fixed
* Appids: 295060, 303250, 301710, 292750

Those changes should be visible after public db is deployed and cache is refreshed (24h)

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "- Arcane preRaise -"

* 5 apps fixed
* Appids: 609796, 609795, 609794, 609793, 609792, 609791, 603780
* _609796, 609795, 609794, 609793, 609792, 609791  have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "3DCoat"

* 4 apps fixed
* Appids: 257610, 255050, 234570, 219210
* _219210 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Music Creator 6 Touch"

* 15 apps fixed
* Appids: 297140, 245810, 215850, 261160, 257320, 222710, 293080, 285630, 285620, 285610, 241090, 241490, 241230, 241970, 241960
* _293080, 285630, 285620, 285610, 241090, 241490, 241230, 241970 and 241960 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Agarest: Generations of War"

* 60 apps fixed
* Appids: 372710, 505060, 307940, 437220, 306660, 567780, 374240, 504800, 46560, 372960, 438240, 251080, 265130, 259240, 222630, 268710, 255140, 208790, 259220, 242270, 249910, 246050, 237070, 215310, 237890, 241150, 240890, 240120, 241140, 239860, 240880, 240110, 241130, 240870, 240100, 241120, 240860, 240850, 240080, 240840, 240070, 240060, 240040, 241060, 241050, 240020, 241040, 240990, 239950, 239940, 240950, 239920, 240940, 240930, 239900, 240150, 239890, 240910, 240140, 239880, 240130
* _241150, 240890, 240120, 241140, 239860, 240880, 240110, 241130, 240870, 240100, 241120, 240860, 240850, 240080, 240840, 240070, 240060, 240040, 241060, 241050, 240020, 241040, 240990, 239950, 239940, 240950, 239920, 240940, 240930, 239900, 240150, 239890, 240910, 240140, 239880 and 240130 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Sins of a Dark Age"

* 4 apps fixed
* Appids: 267830, 254260, 238900, 237620, 215860, 251970, 270900
* _270900 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Who Wants To Be A Millionaire?"

* 4 apps fixed
* Appids: 257610, 255050, 234570, 219210

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Tomb Raider"

* 24 apps fixed
* Appids: 213900, 210060, 267660, 208790, 8000, 391220, 225320, 225300, 225020, 225000, 208800, 849310, 905320, 237450, 849170, 849180, 974630, 541750, 750920, 8009, 7000, 8030, 849260, 7030, 849300
* _7030, 8030, 237450, 541750, 849170, 849180, 974630 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Flow DJ Software"

* 3 apps fixed
* Appids: 277770, 257290, 264970

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "America's Army: Proving Grounds"

* 3 apps fixed
* Appids: 249730, 203290, 239490

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Resident Evil 4"

* 4 apps fixed
* Appids: 235140, 273540, 254700, 272260
* _272260 have been removed from db._

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Scrabble"

* 4 apps fixed
* Appids: 258420, 240500, 236660, 234100

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
### Update "Dead island riptide JP"

* 2 apps fixed
* Appids: 244060, 240220

Those changes should be visible after public db is deployed and cache is refreshed (24h)

**Comment by gsabater** [comment]
@MakoSipper 

I have finished to refresh all detected games with wrong games.
Database will be refreshed tomorrow, and any spare game that needs to be updated but I haven't detected, should be automatically updated at most by September, even those are mostly DLCs

Closing the issue
