### ISSUE TITLE
[BUG] Game with wrong name

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#86]
![chrome_2019-08-09_12-38-06](https://user-images.githubusercontent.com/16372995/62791031-b96e6980-baa2-11e9-8d24-74e66d6aba30.png)
Hyperdimension Neptunia Re;Birth2: Sisters Generation
https://store.steampowered.com/app/351710/Hyperdimension_Neptunia_ReBirth2_Sisters_Generation/

**Comment by gsabater** [comment]
Hello @MakoSipper 
This is related to the unfamous #82 

I have manually solved this specific game. Database will be refreshed tomorrow.

Any other games afftected by this issue should be updated at most by september.

Thanks for the feedback!
