### ISSUE TITLE
[BUG] "With achievements" filter not working correctly

### ISSUE THREAD

**Issue by MakoSipper** [gsabater/Steam-Backlog#87]
Many games without achievements still show with the filter on, not sure why. Only a few (about 100 out of 3800) seem to be hidden this way, not sure why either.

**Comment by gsabater** [comment]
Hello @MakoSipper 

Can you please tell me some examples?
names and appids are ok

**Comment by MakoSipper** [comment]
https://store.steampowered.com/app/556180/Mysterium_A_Psychic_Clue_Game/

Doesn't get filtered out when I select "With achievements", although it doesn't have them.

**Comment by gsabater** [comment]
You are right,
for some reason, this game has 0 achievements (which technically is different to no achievements).

I'll solve this asap.
Thanks

**Comment by gsabater** [comment]
@MakoSipper 
This should already be addressed

---

Fixed in October 2019 release.
Complete changelog at https://steam-backlog.com/changelog
