### ISSUE TITLE
"Something went wrong when saving your data" when trying to create a collection

### ISSUE THREAD

**Issue by ahal** [gsabater/Steam-Backlog#89]
STR:
Right click a game.
Select the "Collections" tab
Select "Create new collection"
Enter a name and press "Create"

Result:
A toast with the text "Something went wrong when saving your data" appears near the bottom of the page.

Note, I'm using Firefox and I've disabled adblockers.

**Comment by enchained** [comment]
Chrome:
```
Cannot read property 'className' of null
    at classList (bundle.js:3392)
    at addClass (bundle.js:3390)
    at Object.NProgress.render (bundle.js:3378)
    at Object.NProgress.set (bundle.js:3374)
    at Object.NProgress.start (bundle.js:3374)
    at Store.saveCollection (bundle.js:5987)
    at Array.wrappedActionHandler (bundle.js:5783)
    at Store.dispatch (bundle.js:5763)
    at Store.boundDispatch [as dispatch] (bundle.js:5758)
    at Store.createCollection (bundle.js:5983)
```
probably cause `parent = document.querySelector(Settings.parent)` results in `null`

**Comment by gsabater** [comment]
Hello @ahal , sorry for the delay in answering,

I have been looking into this and in fact I have received error reports about it as well.
Looks like there is something wrong with one of the changes i made recently. The backend is not registering the selected game at the moment to create the collection, and is rejecting the request because collections can't be empty.

I'm going to take a look at reply here as soon as I have fixed this.
Thanks a lot for your feedback.

**Comment by gsabater** [comment]
Hello @enchained 
This is another issue not related to the OP.

The problem you report is an issue with a javascript plugin called NProgress. I have been thinking to use it for a while, but ended not doing it. I'm also going to see where is invoked and I will remove the references as well.

Thanks for your feedback!

**Comment by gsabater** [comment]
Hello @ahal 
The issue has been corrected.

Thanks a lot for your feedback. Feel free to reopen the issue if you encounter more problems, or open a new one if you find something unrelated.

---

Fixed ~ September 2019
Complete changelog at https://steam-backlog.com/changelog

**Comment by ahal** [comment]
Thanks @gsabater!

Also thanks in general for the great app, your hard work is very much appreciated.

**Comment by enchained** [comment]
@gsabater Thanks for fixing it back then, but now it looks like it doesn't work again. Can't save the new collection. It gives an error message: Something went wrong when saving.
Is the collection endpoint down?
```
bundle.js?v=3-9-25:1164 POST https://steam-backlog.com/api/collection/store 500
send @ bundle.js?v=3-9-25:1164
ajax @ bundle.js?v=3-9-25:1142
jQuery.<computed> @ bundle.js?v=3-9-25:1154
saveCollection @ bundle.js?v=3-9-25:5360
wrappedActionHandler @ bundle.js?v=3-9-25:5139
dispatch @ bundle.js?v=3-9-25:5118
boundDispatch @ bundle.js?v=3-9-25:5112
createCollection @ bundle.js?v=3-9-25:5355
wrappedActionHandler @ bundle.js?v=3-9-25:5139
dispatch @ bundle.js?v=3-9-25:5118
boundDispatch @ bundle.js?v=3-9-25:5112
save @ vue.component.collection-editor.js?v=3-9-25:4
click @ VM17611:3
invokeWithErrorHandling @ bundle.js?v=3-9-25:3878
invoker @ bundle.js?v=3-9-25:3910
original._wrapper @ bundle.js?v=3-9-25:4497

bundle.js?v=3-9-25:5361 Uncaught ReferenceError: jxr is not defined
    at Object.<anonymous> (bundle.js?v=3-9-25:5361)
    at fire (bundle.js?v=3-9-25:730)
    at Object.fireWith [as rejectWith] (bundle.js?v=3-9-25:736)
    at done (bundle.js?v=3-9-25:1150)
    at XMLHttpRequest.<anonymous> (bundle.js?v=3-9-25:1163)
```

request details:
url: https://steam-backlog.com/api/collection/store

form data:
collection%5Bname%5D=My+new+collection&collection%5Bapps%5D%5B%5D=400&collection%5Bapps%5D%5B%5D=620&collection%5Bapps%5D%5B%5D=684410&collection%5Bis_new%5D=true&collection%5Bis_public%5D=true&collection%5Bnew_poster%5D=false&_token=ecNYcyhSh8W3OlrTnrJ1YZITrCvWCB6qxF5bmpw2

response: {message: "Server Error"}

**Comment by gsabater** [comment]
@enchained thanks for bringing this to me.
I have made several changes to the site and i'm planning a release for this month.
I probably have messed something up, and I should take a look at this, but i wont be able to do it in less than a week or two.

Thanks for pointing me to this, i will investigate this and reach you once this is solved.
