### ISSUE TITLE
[Bug] Wrong skipped games number after sorting

### ISSUE THREAD

**Issue by enchained** [gsabater/Steam-Backlog#92]
I suppose since not all games have the data that is used by specific sorting, some are getting skipped in the process. For example, I open a list of 40 games, and if I sort it by HLTB - Fastest, it shows like "Displaying 28 results. Skipped 0 elements". I think it should probably say that 12 other elements were skipped then.

**Comment by gsabater** [comment]
Hey @enchained 

Can you please give me a screenshot?
Indeed, when sorting games, items without the sorting criteria (a score, HLTB, etc) are skipped.
The explanation of what games and why some games have been skipped can be improved tho.

Give me the list giving you problems and i will take a look.

**Comment by enchained** [comment]
Hi. For example, this is my list: https://steam-backlog.com/u/enchained/next When I sort by HLTB or Steam score for example, the games number is decreased, while the skipped number is always 0.

> The explanation of what games and why some games have been skipped can be improved tho.

It would be nice to see something like "skipped due to sorting/filters" and "click to reset" next to it

**Comment by gsabater** [comment]
Perfect, I will take a look and return back.
Thanks for the feedback.

I was thinking about adding something useful to the lists/collections, for example graphs and stats. Any ideas about what could be useful or cool?

**Comment by gsabater** [comment]
Hello again @enchained 

Following your suggestions, i have made a few updates to the whole explanation system.
Now the howlongtobeat reason is reflected instead of just decreasing the number of games in the collection without giving an explanation of why.

The skipped games are shown as well, and each filter has a button to remove it. Do you think its intuitive? 

Please, see this screen, and tell me what you think.
I plan to release this on the following days, and I'm very interested in knowing more ways to update and improve the filtering (or any other) system.

https://imgur.com/ovaS4pq

**Comment by enchained** [comment]
Hi. I think it looks great! It's really detailed and looks like a more flexible system now. Looking forward to the release. 

As for the ideas, I think I had some, I'll think more and create some feature requests when I'll have more time. One idea was about completion progress (via achievements import or manual percentage), another thought was about tag exclusion (show games without that tag), "hide vr-only games" filter like in Steam labs search (not every vr game is vr-only, not sure if Steam data you have access to allows to differ).

Also I noticed that you started to use Steam posters in collections now. Since not everyone uploaded a poster in the new forum, some collections may now look inconsistent. The ways to fix it: view selection - poster grid, a banner grid like before, a list, table, etc. Another way - like what Steam does now - allow users with need to upload their posters, but it sounds complex since it's not a local library we're talking about. 
Sorry for the offtopic and thank you for continuing your hard work.

**Comment by gsabater** [comment]
@enchained thanks for your comments.
As the topic related to the explanation in skipped games is resolved, im going to close this issue.

Please, open new issues for every new problem or idea you might have and i can work on them as well.

just as an ending note, i won't enable users to upload any kind of media to the website for security reasons. But i will add a new visibility option to enable or disable vertical posters on collections and the browse tool.

![vertical](https://user-images.githubusercontent.com/4948172/76707620-05485780-66f1-11ea-9b40-ee80959ea18a.png)

Thanks
