### ISSUE TITLE
[Bug] Can't change status of games

### ISSUE THREAD

**Issue by screwll** [gsabater/Steam-Backlog#94]
When i try to press the button to change status of games nothing happens, can't even press the button.

**Comment by gsabater** [comment]
Hello @screwll, thanks for reaching out.

Can you please tell me what operating system and browser are you using?
If possible, you can also send me a screen recording or at least a screenshot.

Thanks a lot!

**Comment by screwll** [comment]
Windows 10 and Firefox, I tried with a diferent browser and even in the phone browser but is the same.
Here is a video https://streamable.com/9d5qit
When i log out i can press the button normally as shown in the video.

**Comment by gsabater** [comment]
Hola @screwll,

después de ver el vídeo creo que podemos hablar en castellano tranquilamente.
Ya veo lo que te ocurre, sin embargo, es algo extraño ya que con firefox no puedo reproducirlo.

Imagino que este sistema si que debía funcionarte en algún momento porque veo que tienes algunos juegos catalogados como favoritos ya.

Si fueras tan amable de entrar en la web, y darle a botón derecho -> inspeccionar. Te saldrá una ventana emergente o acoplada a la parte inferior de la pantalla, y ahi seleccionas la pestaña consola.

Si hay errores deberían salir con un texto de color rojo, crees que podías hacerme una captura de eso? Si no hay ninguno, prueba a intentar abrir la ventanita de status mientras mantienes la consola abierta.

Muchisimas gracias

**Comment by screwll** [comment]
Ahi lo abri y me sale todo esto 
![Captura de pantalla (127)](https://user-images.githubusercontent.com/63386297/79024323-fa021380-7b58-11ea-989b-6bad49400e99.png)
![Captura de pantalla (128)](https://user-images.githubusercontent.com/63386297/79024325-fbcbd700-7b58-11ea-811d-934f03bdbaf8.png)

**Comment by gsabater** [comment]
Muchísimas gracias.

Parece que con esto puedo ir investigando.
Lo miro y te digo cosas lo antes posible.

Dejo la issue abierta

**Comment by gsabater** [comment]
Hola @screwll ,

ya debería estar solucionado tu error. Parece que hubo un problema con una de tus colecciones que se guardó vacía, y eso hacía que hubiera unos errores que no permitían continuar los scripts correctamente.

Muchísimas gracias por tu apoyo, no dudes en volver a crear incidencias si tienes cualquier otro problema.

---

Fixed @ Spring 2020
Complete changelog at https://steam-backlog.com/changelog
