### ISSUE TITLE
[Bug] Compact view displays icons full size

### ISSUE THREAD

**Issue by VengefulSquid** [gsabater/Steam-Backlog#95]
Compact view displays icons at same size as comfortable mode but one by one vertically. I'm new to this site but I think they are supposed to be smaller than comfortable.  
![steambacklog](https://user-images.githubusercontent.com/14372672/85056421-1c3a9200-b197-11ea-916e-ffbfe99b3b31.PNG)

**Comment by gsabater** [comment]
Hello @GentlemanSquid 

First of all, thanks for your feedback and welcome.

It's possible for you to give me a screenshot where I can see at least two posters?

Also, what browser are you using?

Does this happen without filters as well?

Thanks

**Comment by VengefulSquid** [comment]
Thank you. I am using Chrome on Windows 10. Its the same without filters.

![sb1](https://user-images.githubusercontent.com/14372672/85065623-66c30b00-b1a5-11ea-9b06-1617decf56dd.png)
![sb2](https://user-images.githubusercontent.com/14372672/85065625-675ba180-b1a5-11ea-8a30-12d54fa849d7.png)
![sb3](https://user-images.githubusercontent.com/14372672/85065616-6460b100-b1a5-11ea-9731-37d421b50f82.png)
![sb4](https://user-images.githubusercontent.com/14372672/85065619-6591de00-b1a5-11ea-91ec-8b78c977188b.png)
![sb5](https://user-images.githubusercontent.com/14372672/85065621-662a7480-b1a5-11ea-83b6-2487fba12d26.png)

**Comment by gsabater** [comment]
Thanks a lot for the screens.
I have more questions to help figuring what might be wrong:

- Can you check that your chrome is updated?, This is done under the chrome menu > about chrome
- does this happen on your library or also on the " all games" tab?
- can you check on incognito? You don't need to login, just go to browse all games.
- can you check again on other browser you might have installed?

Thank you again

**Comment by VengefulSquid** [comment]
- Yes my chrome is up to date. 

- Happens on all games too.

- Happens on incognito mode as well.

- Happens in latest update of firefox and edge.

I'm happy to supply more images and answers.

**Comment by gsabater** [comment]
Hello @GentlemanSquid 

Thanks again for the heads up, i have been able to reproduce and solve the issue.
The `compact` view should be able working again. I suggest you to use it with vertical posters because with the other small ones I find it a bit oppresive.

You might need to have your caché flushed before seeing it correctly.

Thanks again, and don't doubt to open a new issue if you find any bugs or have any suggestions.

---

Fixed @ Summer 2020
Complete changelog at https://steam-backlog.com/changelog
